server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/study?serverTimezone=Asia/Seoul
    username: study
    password: study
  jpa:
    database: mysql
  redis:
    host: host.docker.internal
    port: 6379

#logging:
#  level:
#    root: error

oauth2:
  redirectUrl: host.docker.internal:3090