server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleact?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    database: mysql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client-secret}
            scope: ${scope}
  redis:
    host: localhost
    port: 6379

oauth2:
  redirectUrl: http://3.39.151.81

sentry:
  dsn: ${sentry_dsn}
  traces-sample-rate: 1.0