spring:
  config:
    activate:
      on-profile: on-restdocs

springdoc:
  swagger-ui:
    disable-swagger-default-url: false
    operations-sorter: method
    path: /docs/api.json
  cache:
    disabled: true
  api-docs:
    path: /docs/api.json
---

spring:
  config:
    activate:
      on-profile: off-restdocs

springdoc:
  swagger-ui:
    enabled: false
---
