server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleact?serverTimezone=Asia/Seoul
    username: sleact
    password: sleact
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: debug