name: deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make properties
        run: |
          cd ./src/main/resources
          echo $APPLICATION_DEV >> application-dev.yml
          echo $APPLICATION_OAUTH >> application-oauth.yml
        env:
          APPLICATION_DEV: ${{ secrets.APPLICATION_DEV }}
          APPLICATION_OAUTH: ${{ secrets.APPLICATION_OAUTH }}
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Transfer script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          source: "./scripts/deploy.sh"
          target: "/deploy/backend"
          strip_components: 2
      - name: Transfer jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          source: "./build/libs/*.jar"
          target: "/deploy/backend"
          strip_components: 2
      - name: Execute script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          script_stop: true
          script: chmod +x /deploy/backend/deploy.sh && sh /deploy/backend/deploy.sh
